//! Configuration file generation for Ferrumyx setup

use crate::security::{generate_secure_password, generate_secure_key};
use ferrumyx_config::{FerrumyxConfig, LlmProviderConfig};
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

/// Configuration generation options
#[derive(Debug, Clone)]
pub struct ConfigOptions {
    pub environment: super::wizard::Environment,
    pub output_dir: PathBuf,
    pub include_env_file: bool,
    pub include_toml_file: bool,
    pub generate_secrets: bool,
}

/// Generate configuration files from FerrumyxConfig
pub async fn generate_config_files(
    config: &FerrumyxConfig,
    options: &ConfigOptions,
) -> Result<(), Box<dyn std::error::Error>> {
    // Create output directory if it doesn't exist
    fs::create_dir_all(&options.output_dir)?;

    if options.include_toml_file {
        generate_toml_file(config, &options.output_dir).await?;
    }

    if options.include_env_file {
        generate_env_file(config, options).await?;
    }

    Ok(())
}

/// Generate ferrumyx.toml configuration file
async fn generate_toml_file(
    config: &FerrumyxConfig,
    output_dir: &PathBuf,
) -> Result<(), Box<dyn std::error::Error>> {
    let toml_path = output_dir.join("ferrumyx.toml");

    // Convert FerrumyxConfig to TOML-compatible structure
    let toml_config = TomlConfig::from(config);

    // Serialize to TOML
    let toml_content = toml::to_string_pretty(&toml_config)?;

    // Add header comment
    let header = r#"# ferrumyx.toml — Ferrumyx configuration
# Generated by ferrumyx-setup on ${DATE}
#
# DO NOT commit API keys to version control!
# Use .env file or environment variables for secrets.

"#.replace("${DATE}", &chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC").to_string());

    let full_content = format!("{}{}", header, toml_content);

    fs::write(&toml_path, full_content)?;
    println!("Generated: {}", toml_path.display());

    Ok(())
}

/// Generate .env file with environment variables
async fn generate_env_file(
    config: &FerrumyxConfig,
    options: &ConfigOptions,
) -> Result<(), Box<dyn std::error::Error>> {
    let env_path = options.output_dir.join(".env");
    let mut env_vars = HashMap::new();

    // Database configuration
    match config.database.backend.as_str() {
        "postgresql" => {
            env_vars.insert("DATABASE_URL".to_string(), config.database.url.clone());
            if options.generate_secrets {
                if config.database.url.contains("${POSTGRES_PASSWORD}") {
                    env_vars.insert("POSTGRES_PASSWORD".to_string(), generate_secure_password(32));
                }
                env_vars.insert("READONLY_PASSWORD".to_string(), generate_secure_password(32));
            }
            env_vars.insert("POSTGRES_USER".to_string(), "ferrumyx".to_string());
            env_vars.insert("POSTGRES_DB".to_string(), "ferrumyx".to_string());
        }
        "sqlite" => {
            env_vars.insert("DATABASE_URL".to_string(), config.database.url.clone());
        }
        _ => {}
    }

    // Redis configuration
    env_vars.insert("REDIS_URL".to_string(), "redis://redis:6379".to_string());
    if options.generate_secrets {
        env_vars.insert("REDIS_PASSWORD".to_string(), generate_secure_password(32));
    }

    // Web server configuration
    env_vars.insert("FERRUMYX_WEB_ADDR".to_string(), "0.0.0.0:3000".to_string());
    env_vars.insert("FERRUMYX_DATABASE_URL".to_string(), config.database.url.clone());
    env_vars.insert("FERRUMYX_REDIS_URL".to_string(), "redis://:${REDIS_PASSWORD}@redis:6379".to_string());

    // LLM provider API keys
    for (provider_name, provider_config) in &config.llm.providers {
        if let Some(api_key) = &provider_config.api_key {
            let env_key = match provider_name.as_str() {
                "openai" => "OPENAI_API_KEY",
                "anthropic" => "ANTHROPIC_API_KEY",
                "gemini" => "GEMINI_API_KEY",
                "openai_compatible" => "OPENAI_COMPATIBLE_API_KEY",
                _ => continue,
            };
            env_vars.insert(env_key.to_string(), api_key.clone());
        }
    }

    // Multi-channel integration
    if let Some(whatsapp) = &config.channels.whatsapp {
        env_vars.insert("WHATSAPP_API_KEY".to_string(), whatsapp.api_token.clone());
    }
    if let Some(slack) = &config.channels.slack {
        env_vars.insert("SLACK_BOT_TOKEN".to_string(), slack.bot_token.clone());
    }
    if let Some(discord) = &config.channels.discord {
        env_vars.insert("DISCORD_BOT_TOKEN".to_string(), discord.bot_token.clone());
    }

    // Security keys
    env_vars.insert("ENCRYPTION_KEY".to_string(), config.security.encryption_key.clone());
    env_vars.insert("JWT_SECRET".to_string(), config.security.jwt_secret.clone());

    // Monitoring
    env_vars.insert("PROMETHEUS_PORT".to_string(), "9090".to_string());
    if options.generate_secrets {
        env_vars.insert("GRAFANA_ADMIN_PASSWORD".to_string(), generate_secure_password(16));
    }
    env_vars.insert("ALERTMANAGER_PORT".to_string(), "9093".to_string());

    // Logging
    env_vars.insert("RUST_LOG".to_string(), format!("info,ferrumyx={},ironclaw=info", config.monitoring.log_level));
    env_vars.insert("LOG_LEVEL".to_string(), config.monitoring.log_level.clone());

    // Environment-specific settings
    match options.environment {
        super::wizard::Environment::Development => {
            env_vars.insert("DEBUG".to_string(), "true".to_string());
            env_vars.insert("HOT_RELOAD".to_string(), "true".to_string());
            env_vars.insert("BIOCLAW_TOOLS_ENABLED".to_string(), "pubmed,blast,pymol,fastqc,fpocket,vina,rdkit,admet".to_string());
        }
        super::wizard::Environment::Production => {
            env_vars.insert("NODE_ENV".to_string(), "production".to_string());
            env_vars.insert("COMPOSE_PROJECT_NAME".to_string(), "ferrumyx-prod".to_string());
        }
    }

    // Docker secrets (production)
    if matches!(options.environment, super::wizard::Environment::Production) {
        env_vars.insert("DB_PASSWORD_FILE".to_string(), "/run/secrets/db_password".to_string());
        env_vars.insert("REDIS_PASSWORD_FILE".to_string(), "/run/secrets/redis_password".to_string());
        env_vars.insert("API_KEYS_FILE".to_string(), "/run/secrets/api_keys".to_string());
    }

    // Generate .env content
    let mut env_content = String::from("# Ferrumyx Environment Configuration\n# Generated by ferrumyx-setup\n\n");

    // Sort keys for consistent output
    let mut sorted_keys: Vec<_> = env_vars.keys().collect();
    sorted_keys.sort();

    for key in sorted_keys {
        if let Some(value) = env_vars.get(key) {
            env_content.push_str(&format!("{}={}\n", key, value));
        }
    }

    fs::write(&env_path, env_content)?;
    println!("Generated: {}", env_path.display());

    // Create .env.example if it doesn't exist
    let example_path = options.output_dir.join(".env.example");
    if !example_path.exists() {
        let example_content = r#"# Ferrumyx Environment Configuration Example
# Copy to .env and fill in values

# Database
DATABASE_URL=postgresql://ferrumyx:${POSTGRES_PASSWORD}@localhost:5432/ferrumyx
POSTGRES_PASSWORD=
POSTGRES_USER=ferrumyx
POSTGRES_DB=ferrumyx
READONLY_PASSWORD=

# Redis
REDIS_URL=redis://redis:6379
REDIS_PASSWORD=

# Web Server
FERRUMYX_WEB_ADDR=0.0.0.0:3000
FERRUMYX_DATABASE_URL=postgresql://ferrumyx:${POSTGRES_PASSWORD}@postgres:5432/ferrumyx
FERRUMYX_REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379

# LLM API Keys (choose one or more)
OPENAI_API_KEY=sk-...
ANTHROPIC_API_KEY=sk-ant-...
GEMINI_API_KEY=
OPENAI_COMPATIBLE_API_KEY=

# Multi-channel Gateway
SLACK_BOT_TOKEN=xoxb-your-slack-token
DISCORD_BOT_TOKEN=your-discord-token
WHATSAPP_API_KEY=your-whatsapp-key
WEBHOOK_SECRET=your-webhook-secret

# Security
ENCRYPTION_KEY=32-char-encryption-key-here
JWT_SECRET=your-jwt-secret-key

# Monitoring
PROMETHEUS_PORT=9090
GRAFANA_ADMIN_PASSWORD=
ALERTMANAGER_PORT=9093

# Logging
RUST_LOG=info,ferrumyx=debug,ironclaw=info
LOG_LEVEL=info

# Development
DEBUG=true
HOT_RELOAD=true

# Production
NODE_ENV=production
COMPOSE_PROJECT_NAME=ferrumyx-prod

# Secrets (Docker secrets in production)
DB_PASSWORD_FILE=/run/secrets/db_password
REDIS_PASSWORD_FILE=/run/secrets/redis_password
API_KEYS_FILE=/run/secrets/api_keys
"#;
        fs::write(&example_path, example_content)?;
        println!("Generated: {}", example_path.display());
    }

    Ok(())
}

/// TOML-compatible configuration structure
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct TomlConfig {
    // Version
    version: String,

    // Database
    #[serde(rename = "database")]
    database: TomlDatabaseConfig,

    // LLM
    #[serde(rename = "llm")]
    llm: TomlLlmConfig,

    // Security
    #[serde(rename = "security")]
    security: TomlSecurityConfig,

    // Performance
    #[serde(rename = "performance")]
    performance: TomlPerformanceConfig,

    // Channels
    #[serde(rename = "channels")]
    channels: TomlChannelsConfig,

    // Monitoring
    #[serde(rename = "monitoring")]
    monitoring: TomlMonitoringConfig,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct TomlDatabaseConfig {
    url: String,
    pool_size: u32,
    backend: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct TomlLlmConfig {
    default_provider: String,
    providers: std::collections::HashMap<String, LlmProviderConfig>,
}



#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct TomlSecurityConfig {
    jwt_secret: String,
    encryption_key: String,
    audit_enabled: bool,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct TomlPerformanceConfig {
    max_concurrent: usize,
    timeout_seconds: u64,
    caching_enabled: bool,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct TomlChannelsConfig {
    enabled: bool,

    #[serde(skip_serializing_if = "Option::is_none")]
    whatsapp: Option<TomlWhatsAppConfig>,

    #[serde(skip_serializing_if = "Option::is_none")]
    slack: Option<TomlSlackConfig>,

    #[serde(skip_serializing_if = "Option::is_none")]
    discord: Option<TomlDiscordConfig>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct TomlWhatsAppConfig {
    api_token: String,
    phone_number_id: String,
    enabled: bool,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct TomlSlackConfig {
    bot_token: String,
    signing_secret: String,
    enabled: bool,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct TomlDiscordConfig {
    bot_token: String,
    application_id: String,
    enabled: bool,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct TomlMonitoringConfig {
    metrics_enabled: bool,
    metrics_endpoint: String,
    log_level: String,
    health_checks_enabled: bool,
}

impl From<&FerrumyxConfig> for TomlConfig {
    fn from(config: &FerrumyxConfig) -> Self {
        TomlConfig {
            version: config.version.clone(),
            database: TomlDatabaseConfig {
                url: config.database.url.clone(),
                pool_size: config.database.pool_size,
                backend: config.database.backend.clone(),
            },
            llm: TomlLlmConfig {
                default_provider: config.llm.default_provider.clone(),
                providers: config.llm.providers.clone(),
            },
            security: TomlSecurityConfig {
                jwt_secret: config.security.jwt_secret.clone(),
                encryption_key: config.security.encryption_key.clone(),
                audit_enabled: config.security.audit_enabled,
            },
            performance: TomlPerformanceConfig {
                max_concurrent: config.performance.max_concurrent,
                timeout_seconds: config.performance.timeout_seconds,
                caching_enabled: config.performance.caching_enabled,
            },
            channels: TomlChannelsConfig {
                enabled: config.channels.enabled,
                whatsapp: config.channels.whatsapp.as_ref().map(|w| TomlWhatsAppConfig {
                    api_token: w.api_token.clone(),
                    phone_number_id: w.phone_number_id.clone(),
                    enabled: w.enabled,
                }),
                slack: config.channels.slack.as_ref().map(|s| TomlSlackConfig {
                    bot_token: s.bot_token.clone(),
                    signing_secret: s.signing_secret.clone(),
                    enabled: s.enabled,
                }),
                discord: config.channels.discord.as_ref().map(|d| TomlDiscordConfig {
                    bot_token: d.bot_token.clone(),
                    application_id: d.application_id.clone(),
                    enabled: d.enabled,
                }),
            },
            monitoring: TomlMonitoringConfig {
                metrics_enabled: config.monitoring.metrics_enabled,
                metrics_endpoint: config.monitoring.metrics_endpoint.clone(),
                log_level: config.monitoring.log_level.clone(),
                health_checks_enabled: config.monitoring.health_checks_enabled,
            },
        }
    }
}